### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by satanas** [satanas/libturpial#32]
Apparently, libturpial 1.0 is done so it's time to update it documentation

**Comment by FabioRosado** [comment]
You might already know  about this but I've just forked the libturpial and while building the documentation on sphinx there were couple files that failed to be created

**Comment by satanas** [comment]
@FabioRosado Could you tell me which files failed? And, if possible, paste the output of sphinx

**Comment by FabioRosado** [comment]
@satanas I tried to build it again and it built with less warnings, at the moment I just got two:

Running Sphinx v1.1.3  
loading pickled environment... not yet created  
building [html]: all source files
updating environment: 7 added, 0 changed, 0 removed
reading sources... [100%] quickstart  
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/fabiorosado/GitHub/libturpial2/docs/common.rst:: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] quickstart  
writing additional files... genindex py-modindex search
copying static files... WARNING: html_static_path entry '/home/fabiorosado/GitHub/libturpial2/docs/_static' does not exist
done
dumping search index... done
dumping object inventory... done
build succeeded, 2 warnings.

**Comment by satanas** [comment]
I see, but this time it built all the documentation files?

**Comment by FabioRosado** [comment]
Yes this time it just built everything, perhaps the first time I tried to build the folder wasn't up to date

**Comment by satanas** [comment]
Great! Then everything is OK.

I'm gonna close this issue, if you see this behavior again please report it as an issue.
