### ISSUE TITLE
AccountManager instance has no attribute 'get_all'

### ISSUE THREAD

**Issue by guerrerocarlos** [satanas/libturpial#56]
> > > a = Core()
> > > a.get_all_friends_list()
> > >    Traceback (most recent call last):
> > >      File "<stdin>", line 1, in <module>
> > >      File "libturpial/api/core.py", line 241, in get_all_friends_list
> > >        """
> > >    AttributeError: AccountManager instance has no attribute 'get_all'

**Comment by satanas** [comment]
Good catch bro! Gonna check it right now :)

**Comment by satanas** [comment]
Fixed on 8a8099c. Closing
